window.SEED_LISTINGS = [
  // ── ACTIVE ────────────────────────────────────────────────────────────────
  {
    id: "airbnb-locked",
    title: "Noe Valley Airbnb",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "Airbnb",
    link: "https://www.airbnb.com/rooms/1249546685248852405?unique_share_id=1e1e7b2d-a532-4b4a-b2b7-3b7ad57b6d52&viralityEntryPoint=1&s=76",
    rent: 8500,
    rentPerPerson: 2125,
    beds: null,
    baths: null,
    status: "locked in",
    topChoice: true,
    applied: true,
    pinned: true,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "2026-06-15T17:00",
    hasTour: true,
    leaseStart: "2026-08-17",
    leaseEnd: "2027-06-07",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Discounted lease: $8,500/month. Isabella will send offer Saturday June 14.",
    afterTourNotes: "",
    photos: [],
    announcements: ["TOP CHOICE — LOCKED IN", "Tour: Monday June 15 at 5pm", "Isabella sending offer Saturday June 14"]
  },
  {
    id: "irving-2547",
    title: "2547 Irving St",
    address: "2547 Irving St Unit 2545, San Francisco, CA",
    neighborhood: "Outer Sunset",
    source: "Apartments.com",
    link: "https://www.apartments.com/2547-irving-st-san-francisco-ca/1zqkxw4/",
    rent: 7900,
    rentPerPerson: 1975,
    beds: 6,
    baths: 2.5,
    status: "in the running",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 16,
    minutesToTransit: null,
    commuteNotes: "Three shuttle options, 16 min walk. Commute to MTV is 1 hr 40 min.",
    videoTour: "",
    notes: "No competition, negotiable. 6 rooms, 2.5 baths. Biggest room $2,200/mo; other rooms $1,933/person. Natural light better in smaller rooms. Furnished. Photos in album.",
    afterTourNotes: "Raunak toured. Area is super quiet, Chinatown vibes, likely Uber for bars. 20 min walk from beach. No AC, only heater.",
    photos: [],
    announcements: ["No competition — negotiable on price", "Raunak has toured"]
  },
  {
    id: "24th-2643",
    title: "2643 24th St",
    address: "2643 24th St, San Francisco, CA 94110",
    neighborhood: "Mission",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/2643-24th-St-San-Francisco-CA-94110/2126924844_zpid/",
    rent: 7500,
    rentPerPerson: 1875,
    beds: 4,
    baths: 1,
    status: "in the running",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 3,
    minutesToTransit: null,
    commuteNotes: "Lots of shuttle options, 3–12 min walk depending on stop and time.",
    videoTour: "https://www.dropbox.com/scl/fi/ylo8dxoxgpfbiwlehgnir/2643-24th-St-VT.mov?rlkey=5b61csrgp39pwzt1pdckddg41&e=1&st=j1iyb9id&dl=0",
    notes: "4 bed, 1 bath + office. Bathroom split — shower and toilet are separate rooms. $7,500/mo total, $1,875/person.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "duboce-129",
    title: "129 Duboce Ave",
    address: "129 Duboce Ave, San Francisco, CA 94103",
    neighborhood: "Hayes Valley",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/129-Duboce-Ave-San-Francisco-CA-94103/2099512266_zpid/",
    rent: 8492,
    rentPerPerson: 2123,
    beds: 4,
    baths: 2,
    status: "touring",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "2026-06-09T16:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 10,
    minutesToTransit: null,
    commuteNotes: "Lots of shuttles, prime location, 10–20 min walk depending on stop and time.",
    videoTour: "https://zillow.com/r/2t59zb8f54kt4",
    notes: "4 bed, 2 bath. Hayes Valley. $2,123/person.",
    afterTourNotes: "Didn't like the area, wasn't safe. No AC. Not good vibes — landlord wasn't answering questions well. Same price as Isabella's place.",
    photos: [],
    announcements: []
  },

  {
    id: "van-ness-861",
    title: "861 S Van Ness Ave",
    address: "861 S Van Ness Ave, San Francisco, CA 94110",
    neighborhood: "Mission",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/861-S-Van-Ness-Ave-San-Francisco-CA-94110/351121180_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "touring",
    topChoice: false,
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "2026-06-14T13:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Tour Sunday June 14, 1–3pm.",
    afterTourNotes: "",
    photos: [],
    announcements: ["Tour: Sunday June 14, 1–3pm"]
  },
  {
    id: "banks-467",
    title: "467 Banks St",
    address: "467 Banks St, San Francisco, CA 94110",
    neighborhood: "Mission / Bernal Heights",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/467-Banks-St-San-Francisco-CA-94110/111924564_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "touring",
    topChoice: false,
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "2026-06-13T14:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Tour Saturday June 13, 2pm.",
    afterTourNotes: "",
    photos: [],
    announcements: ["Tour: Saturday June 13, 2pm"]
  },
  {
    id: "sf-94118-undisclosed",
    title: "Undisclosed Address — Inner Richmond",
    address: "San Francisco, CA 94118",
    neighborhood: "Inner Richmond",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/(Undisclosed-Address)-San-Francisco-CA-94118/2083003247_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "touring",
    topChoice: false,
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "",
    removalReason: "",
    tourDate: "2026-06-12T17:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Tour Friday June 12, 5pm. Address is undisclosed — check Zillow link for details.",
    afterTourNotes: "",
    photos: [],
    announcements: ["Tour: Friday June 12, 5pm"]
  },

  // ── ARCHIVE ───────────────────────────────────────────────────────────────
  {
    id: "airbnb-48202551",
    title: "Airbnb — Unknown",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "Airbnb",
    link: "https://www.airbnb.com/rooms/48202551?unique_share_id=ee9d120e-bb39-47b5-b09b-278925deefab&viralityEntryPoint=1&s=76",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Sus — didn't respond when asked to tour",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "airbnb-737690085",
    title: "Airbnb — Potrero Hill",
    address: "San Francisco, CA",
    neighborhood: "Potrero Hill",
    source: "Airbnb",
    link: "https://www.airbnb.com/rooms/737690085185459019?unique_share_id=8f8b8c2d-ed0d-41b2-9722-e3c32ab6b13c&viralityEntryPoint=1&s=76",
    rent: 9200,
    rentPerPerson: 2300,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Airbnb — fading out. Not available until November; shared with 3 others (7 person total?)",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,300/person. Ariel said not available until November, shared with 3 other people.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "banks-467",
    title: "467 Banks St",
    address: "467 Banks St, San Francisco, CA 94110",
    neighborhood: "Bernal Heights",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/467-Banks-St-San-Francisco-CA-94110/111924564_zpid/",
    rent: 8888,
    rentPerPerson: 2222,
    beds: 4,
    baths: 1,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Only 1 bathroom",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 22,
    minutesToTransit: null,
    commuteNotes: "22 min walk to shuttle.",
    videoTour: "",
    notes: "$2,222/person. 22 min walk to shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "york-1030",
    title: "1030 York St",
    address: "1030 York St, San Francisco, CA 94110",
    neighborhood: "Potrero Hill",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/1030-York-St-San-Francisco-CA-94110/2083720454_zpid/",
    rent: 7992,
    rentPerPerson: 1998,
    beds: null,
    baths: 1,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Only 1 bathroom",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$1,998/person.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "airbnb-1678468816",
    title: "519 39th Ave (Airbnb)",
    address: "519 39th Ave, San Francisco, CA 94121",
    neighborhood: "Richmond",
    source: "Airbnb",
    link: "https://www.airbnb.com/rooms/1678468816779720688?unique_share_id=3ac1d85a-c354-4d14-8246-2259d5ff4178&viralityEntryPoint=1&s=76",
    rent: 9936,
    rentPerPerson: 2484,
    beds: 4,
    baths: 4,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Too far north",
    tourDate: "2026-06-14T16:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,484/person. 4 bed 4 bath. Raunak + Sama toured Sunday 6/14 at 4pm.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "page-1283",
    title: "1283 Page St",
    address: "1283 Page St, San Francisco, CA",
    neighborhood: "Haight-Ashbury",
    source: "Apartments.com",
    link: "https://www.apartments.com/1283-page-st-san-francisco-ca/95118g4/",
    rent: 12500,
    rentPerPerson: 3125,
    beds: 4,
    baths: 4,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Too expensive",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "Good location for commuters.",
    videoTour: "",
    notes: "$3,125/person. 4 bed 4 bath. Good location for commuters.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "vanness-471",
    title: "471 S Van Ness Ave",
    address: "471 S Van Ness Ave, San Francisco, CA",
    neighborhood: "Mission",
    source: "Apartments.com",
    link: "https://www.apartments.com/471-s-van-ness-ave-san-francisco-ca/sk5c165/",
    rent: 11000,
    rentPerPerson: 2750,
    beds: 4,
    baths: 3,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,750/person. 4 bed 3 bath.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "31st-1587",
    title: "1587 31st Ave",
    address: "1587 31st Ave, San Francisco, CA",
    neighborhood: "Outer Sunset",
    source: "Apartments.com",
    link: "https://www.apartments.com/1587-31st-ave-san-francisco-ca/0rjbb41/",
    rent: 8000,
    rentPerPerson: 2000,
    beds: 4,
    baths: 4,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,000/person. 4 bed 4 bath.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "clarendon-90",
    title: "90 Clarendon Ave",
    address: "90 Clarendon Ave, San Francisco, CA",
    neighborhood: "Twin Peaks",
    source: "Apartments.com",
    link: "https://www.apartments.com/90-clarendon-ave-san-francisco-ca/2te3q59/",
    rent: 15000,
    rentPerPerson: 3750,
    beds: 4,
    baths: 2,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Too expensive — $3,750/person",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$3,750/person. 4 bed 2 bath. Listed as Mission area.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "diamond-601",
    title: "601 Diamond St",
    address: "601 Diamond St, San Francisco, CA",
    neighborhood: "Noe Valley",
    source: "Apartments.com",
    link: "https://www.apartments.com/601-diamond-st-san-francisco-ca/10bmwf5/",
    rent: 6000,
    rentPerPerson: 1500,
    beds: 4,
    baths: 2,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$1,500/person. 4 bed 2 bath. Noe Valley — where Raunak lives now.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "fell-1124",
    title: "1124-1128 Fell St",
    address: "1124 Fell St, San Francisco, CA",
    neighborhood: "Panhandle",
    source: "Apartments.com",
    link: "https://www.apartments.com/1124-1128-fell-st-san-francisco-ca/cwpn6te/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "webster-725",
    title: "725 Webster St",
    address: "725 Webster St, San Francisco, CA 94117",
    neighborhood: "Hayes Valley",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/725-Webster-St-San-Francisco-CA-94117/2071336217_zpid/",
    rent: 9992,
    rentPerPerson: 2498,
    beds: 4,
    baths: 2,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,498/person. 4 bed 2 bath. Hayes Valley.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "25th-3126",
    title: "3126 25th St",
    address: "3126 25th St, San Francisco, CA 94110",
    neighborhood: "Mission",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/3126-25th-St-3126-San-Francisco-CA-94110/462911221_zpid/",
    rent: 8996,
    rentPerPerson: 2249,
    beds: 5,
    baths: 2,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Would need July lease start",
    tourDate: "",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "5 bed 2 bath. $2,249/person for 4 people; $1,799/person for 5 people. Toured. Would need to start July lease.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "oak-702",
    title: "702 Oak St",
    address: "702 Oak St, San Francisco, CA 94117",
    neighborhood: "Hayes Valley",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/702-Oak-St-San-Francisco-CA-94117/2055679134_zpid/",
    rent: 7875,
    rentPerPerson: 1575,
    beds: 5,
    baths: 2,
    status: "archive",
    applied: true,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$1,575/person. 5 bed 2 bath. Hayes Valley. Sama applied — everyone needs to apply.",
    afterTourNotes: "",
    photos: [],
    announcements: ["Sama applied — everyone needs to apply"]
  },
  {
    id: "minna-733",
    title: "733-735 Minna St",
    address: "733 Minna St, San Francisco, CA 94103",
    neighborhood: "SOMA",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/733-735-Minna-St-733-735-San-Francisco-CA-94103/462636250_zpid/",
    rent: 7500,
    rentPerPerson: 1875,
    beds: 4,
    baths: 3.5,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$1,875/person. 4 bed 3.5 bath. SOMA area.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "ashbury-909",
    title: "909 Ashbury St",
    address: "909 Ashbury St #4, San Francisco, CA 94117",
    neighborhood: "Ashbury Heights",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/909-Ashbury-St-4-San-Francisco-CA-94117/2070176878_zpid/",
    rent: 9000,
    rentPerPerson: 2250,
    beds: 4,
    baths: 2.5,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$2,250/person. 4 bed 2.5 bath. Ashbury Heights.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "hyde-1338",
    title: "1338-1340 Hyde St",
    address: "1338 Hyde St #1, San Francisco, CA 94109",
    neighborhood: "Russian Hill",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/1338-1340-Hyde-St-1-San-Francisco-CA-94109/462976500_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "cl-7937975142",
    title: "CL — Modern Spacious Home",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "Craigslist",
    link: "https://sfbay.craigslist.org/sfc/apa/d/san-francisco-modern-spacious-home/7937975142.html",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: true,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Emailed — no further update",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Sama emailed.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "cl-7939521967",
    title: "CL — 5BR 2BA Remodeled",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "Craigslist",
    link: "https://sfbay.craigslist.org/sfc/apa/d/san-francisco-5br-2ba-remodeled/7939521967.html",
    rent: null,
    rentPerPerson: null,
    beds: 5,
    baths: 2,
    status: "archive",
    applied: true,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Emailed — no further update",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Sama emailed.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "cl-7939455482",
    title: "CL — Big Sunny Bedroom",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "Craigslist",
    link: "https://sfbay.craigslist.org/sfc/apa/d/san-francisco-big-sunny-bedroom/7939455482.html",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: true,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Emailed — no further update",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Sama emailed.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "cecilia-2317",
    title: "2317 Cecilia Ave",
    address: "2317 Cecilia Ave, San Francisco, CA 94116",
    neighborhood: "West Portal",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/2317-Cecilia-Ave-San-Francisco-CA-94116/15120210_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 12,
    minutesToTransit: null,
    commuteNotes: "12 min walk to shuttle.",
    videoTour: "",
    notes: "Raunak found. 12 min walk to shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "36th-2732",
    title: "2732 36th Ave",
    address: "2732 36th Ave, San Francisco, CA 94116",
    neighborhood: "West Portal",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/2732-36th-Ave-San-Francisco-CA-94116/15125887_zpid/",
    rent: 5876,
    rentPerPerson: 1469,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "27 min walk to shuttle — too far",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 27,
    minutesToTransit: null,
    commuteNotes: "27 min walk to shuttle.",
    videoTour: "",
    notes: "Raunak found. $1,469/person. 27 min walk to shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "victoria-306",
    title: "306 Victoria St",
    address: "306 Victoria St, San Francisco, CA 94132",
    neighborhood: "Ingleside",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/306-Victoria-St-San-Francisco-CA-94132/15193152_zpid/",
    rent: 4700,
    rentPerPerson: 1175,
    beds: null,
    baths: null,
    status: "archive",
    applied: true,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "26 min walk to shuttle — too far",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 26,
    minutesToTransit: null,
    commuteNotes: "26 min walk to shuttle.",
    videoTour: "",
    notes: "Raunak applied, gave info, talked to the landlord. $4,700/mo total, $1,175/person. 26 min walk to shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "parker-180",
    title: "180 Parker Ave",
    address: "180 Parker Ave, San Francisco, CA 94118",
    neighborhood: "Jordan Park",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/180-Parker-Ave-San-Francisco-CA-94118/2078416062_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "2026-06-13T14:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "Raunak toured Saturday 6/13 2-4pm. Spacious two-level home in Jordan Park — near Presidio and Golden Gate Park, 2 blocks from USF, short walk to Trader Joe's and Target.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "bancal-sf",
    title: "BanCal SF Listing",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "BanCal",
    link: "https://www.bancalsf.com/listings/detail/e33878d4-42f9-4b8d-b61f-f7b543934812",
    rent: null,
    rentPerPerson: 3200,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Too expensive",
    tourDate: "2026-06-10T00:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 11,
    minutesToTransit: null,
    commuteNotes: "11 min walk to shuttle.",
    videoTour: "https://www.youtube.com/watch?v=mPF1CnMtz8w&t=1s",
    notes: "$3,200/person (or $2,600/person with a 5th roommate). Raunak toured 6/10. 11 min walk to shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  },
  {
    id: "rent415-purplerain",
    title: "Purple Rain (rent415)",
    address: "San Francisco, CA",
    neighborhood: "",
    source: "rent415",
    link: "https://rent415.com/purple-rain/",
    rent: 7000,
    rentPerPerson: 1750,
    beds: 4,
    baths: 1,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Only 1 bathroom",
    tourDate: "",
    hasTour: false,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: null,
    minutesToTransit: null,
    commuteNotes: "",
    videoTour: "",
    notes: "$7,000/mo total, $1,750/person. 4 bed 1 bath. Fully furnished. Landlord is lowkey down for parties.",
    afterTourNotes: "",
    photos: [],
    announcements: ["Fully furnished"]
  },
  {
    id: "vanness-861",
    title: "861 S Van Ness Ave",
    address: "861 S Van Ness Ave, San Francisco, CA 94110",
    neighborhood: "Mission",
    source: "Zillow",
    link: "https://www.zillow.com/homedetails/861-S-Van-Ness-Ave-San-Francisco-CA-94110/351121180_zpid/",
    rent: null,
    rentPerPerson: null,
    beds: null,
    baths: null,
    status: "archive",
    applied: false,
    pinned: false,
    dateFound: "2026-06-10",
    dateRemoved: "2026-06-10",
    removalReason: "Archived",
    tourDate: "2026-06-14T13:00",
    hasTour: true,
    leaseStart: "",
    leaseEnd: "",
    minutesToShuttle: 20,
    minutesToTransit: null,
    commuteNotes: "20 min walk from shuttle.",
    videoTour: "",
    notes: "Raunak touring June 14, 1-3pm. 20 min walk from shuttle.",
    afterTourNotes: "",
    photos: [],
    announcements: []
  }
];
